### ISSUE TITLE
Launch 'Hello world'

### ISSUE THREAD

**Issue by lukefretwell** [cagov/Alpha#10]
- [x] finalize content/call-to-action ([Document)](https://docs.google.com/document/d/1cSDP9aXEZ_QRxAI_SNTqofKs64P9GduXFaYt9AZqsNE/edit)
Survey link:  https://www.surveymonkey.com/r/AlphaCAgov
- [x] update Public Sans files (#17)
- [x] finalize/set-up hosting
- [x] clean up code/design (https://github.com/cagov/Alpha/issues/11)
- [x] add analytics (https://github.com/cagov/Alpha/issues/5)
- [x] publish files
- [x] submit DNS request
- [x] map DNS
- [x] Make sure the meta description is what we want it to say (see below what it currently is).
- [x] Remove the commented code that's not being used.
- [x] Alphabar should be #000000. OK for the official bar to be like it is in the comp (or just make it #000000).
- [x] The state in between the 'Hello' and 'California' isn't working on mobile, but we should really keep it above and not insert images in between structured mark-up.
- [x] Remove the space between paragraphs and 'Team Alpha.CA.gov.' If we feel like there needs to be more paragraph space, add it to the CSS.
- [x] Apply user feedback in next iteration, experimental language, (along with minimum wage page live).

**Comment by abquirarte** [comment]
@lukefretwell on the submit the DNS request task- do you mean alpha.ca.gov? We have that already. We just need to know where to point it to. [in my best tech understanding haha]

**Comment by lukefretwell** [comment]
@abquirarte 👍 

I keep refreshing alpha.ca.gov but still don't see anything. 😆

**Comment by abquirarte** [comment]
see #13

**Comment by humancenteredhuman** [comment]
Fellow Californians,

We’re reimagining [CA.gov](https://ca.gov/) with and for the people of California.

Our first step: Make CA.gov easier for Californians to use. We’re working to help you access the services and information you need. 

And we invite you to join us. 

**Follow our progress** 
We're sharing our work and insights on our [blog](https://medium.com/cadotgov), [Twitter](https://twitter.com/CAdotGov) and [GitHub](https://github.com/cagov/). 

**Contribute your feedback**
Please take our [five-minute survey](https://www.surveymonkey.com/r/AlphaCAgov) to help improve CA.gov. Thanks in advance for sharing your thoughts. 

We’re excited to work with you.

_Team [Alpha.CA.gov](https://alpha.ca.gov/)_

**Comment by jpetrucione** [comment]
I suggest changing the link in the sign off to the Twitter feed. 
1 - this will help build our following
2 - linking back to the website itself (where the user already is) doesn't make sense

**Comment by lukefretwell** [comment]
@jpetrucione from an accessibility perspective you link to what's been described, so since we we don't reference the URL anywhere else, that's why it's linked. I'll just remove the link for now.

**Comment by jpetrucione** [comment]
perfect - thanks

**Comment by jpetrucione** [comment]
@lukefretwell - I suggest changing the "Official California State Website" bar to match CA.gov. As a user, I wld be suspicious of the one here since it doesn't match what I believe/know to be the official site. 
<img width="1428" alt="Official CA gov bar" src="https://user-images.githubusercontent.com/58194407/70572643-09466580-1b55-11ea-8fa9-d30781ae12db.png">

**Comment by lukefretwell** [comment]
@jpetrucione re: above official bar comment, is this still a concern? I'd prefer not to go down the 'let's make things look like the current' site road since we're reimagining.

**Comment by humancenteredhuman** [comment]
Based on user feedback from Friday's session, I have a few changes to the landing page content. People said the writing was simple and conversational, but they still wanted to know more about: 

- Who we are

- What is Alpha.CA.gov

- When we started

_Changes in bold:_ 

Fellow Californians,

**We're a small but mighty team of public servants and outside experts in user research and design. Together, w**e're reimagining CA.gov with and for the people of California. 

Our first step: Make CA.gov easier for Californians to use. **We've been working** to help you access the services and information you need **since December 2019**. 

And we invite you to join us.

Follow our progress
We're sharing **our insights on our blog and Twitter. Our work in progress will live on GitHub and this website, Alpha.CA.gov.** 

Share your feedback
Please take our five-minute survey to help improve CA.gov. Thanks in advance for sharing your thoughts.

We're excited to work with you.

Team Alpha.CA.gov

**Comment by abquirarte** [comment]
Closing this issue! Yay! Other issues will document ongoing iterations of this. 

Screenshots:

![image](https://user-images.githubusercontent.com/9556188/70954377-cdfad980-2021-11ea-8afa-30edbbcb5d32.png)


![image](https://user-images.githubusercontent.com/9556188/70954384-d4895100-2021-11ea-9a7a-b10377f31405.png)
