### ISSUE TITLE
Update "homepage" considerations

### ISSUE THREAD

**Issue by abquirarte** [cagov/Alpha#299]
What changes do we want to make for Release 2? 

Done:

- Play with color- purple 
- Updates to content types and live prototypes

- [ ] - Search (https://github.com/cagov/Alpha/issues/201) push to release 3
- [ ] - Settings (https://github.com/cagov/Alpha/issues/168) push to release 3
- [ ] - Categorization (no issue created, but prototype here: https://cwds.dev/docs/4.3/templates/all-services/) push to release 3
- [ ] -  General use statements https://github.com/cagov/Alpha/issues/232  push to release 3
