### ISSUE TITLE
Release 2 Checklist

### ISSUE THREAD

**Issue by abquirarte** [cagov/Alpha#303]
# Master List for Release 2

## General Changes
- [x] Automated end to end testing https://github.com/cagov/Alpha/issues/319 
- [x] [**List of Bugs/Browser testing on staging site** ](https://docs.google.com/spreadsheets/d/1jIU0bRGKC4WlODOV2Od95M5Q9Q3c6lW4Wx4lspPxVaw/edit#gid=183527542)
- [x] Play with color- purple (from 299)
- [x] Updates to content types and live prototypes (from 299)
- [x] Discuss and agree "show all"
- [x] Discuss and agree "print"
- [x] Discuss and agree title bar being big
- [x] Discuss and agree spacing at the bottom of each page About, news, etc
- [x] Discuss how to represent the passion and pride people have in CA (color or design) - or that black and white feels depressing (and some of the content is sad - e.g. food banks) and dull
- [x] Per Luke's comment: can you remove the California outline in the jumbo and left-align the text?

### Minimum Wage
- [x] Release testing checklist: https://github.com/cagov/Alpha/issues/333

### Food Banks
- [x] Release testing checklist: #344 

### Licensed contractor
- [x] Inconsistent spacing on step 4 licensed contractor, around the "Or"

# New Stories

### CalGrants https://github.com/cagov/UX/issues/35 

- [x] Release testing list: https://github.com/cagov/Alpha/issues/334

### Disability Insurance https://github.com/cagov/UX/issues/72

- [x] Release testing list: https://github.com/cagov/Alpha/issues/336

# For Next Week 2/10/2020

### General
- [ ] Add semantic HTML (https://github.com/cagov/Alpha/issues/309)  - moved to Release 3
- [x] Hyperlinks vs buttons 
- [x] Consistent treatment of OR - or agree that it's going to be different 
- [x] OR in Spanish page- CalGrant
- [ ] Homepage Considerations https://github.com/cagov/Alpha/issues/299 - moved to Release 3
- [x] Blog post
- [x] food banks text inside js need to be translated into chinese

### Road Conditions https://github.com/cagov/UX/issues/37

- [x] Promote Road Conditions from UX to Alpha Repo https://github.com/cagov/Alpha/issues/359

**Comment by abquirarte** [comment]
Notes: 
Translation
Automated testing

**Comment by lukefretwell** [comment]
@artuoma can you remove the California outline in the jumbo and left-align the text?

**Comment by KimberlyglennTSM** [comment]
Remaining open items - moved to Release 3 #387
