### ISSUE TITLE
Master List for Release 3

### ISSUE THREAD

**Issue by KimberlyglennTSM** [cagov/Alpha#387]
# Master List for Release 3

# General

- [x] Fix popup acknowledgment to 24 hours (user should only have to acknowledge once every 24 hours)  **BLOCKS RELEASE 3**
- [x] Fix accessibility bugs https://github.com/cagov/Alpha/issues/432 **BLOCKS RELEASE 3**
- [x] bugs caused by CSS updates https://github.com/cagov/Alpha/issues/435
- [In progress: Chad] Automated end to end testing #471 
- [x] Add semantic HTML (https://github.com/cagov/Alpha/issues/309) 
- [x] Homepage Considerations https://github.com/cagov/Alpha/issues/299~ Beta 
- [x] API Blog post (what shipped, what we prototyped)
- [x] Browser Testing/Bugs List-[Spreadsheet](https://docs.google.com/spreadsheets/d/1jIU0bRGKC4WlODOV2Od95M5Q9Q3c6lW4Wx4lspPxVaw/edit#gid=676928557)
- [X] Send alpha.ca.gov to the list of people that have responded to our survey
Independent worker blog post
- [x] Review survey feedback

**Beta Bridge:** 

- Official state website verification design language: https://github.com/cagov/Alpha/issues/315 @lukefretwell taking lead on this (Beta Bridge)
- Handbook Update
- Release 3 blog post [For Friday]
- Optimize performance https://github.com/cagov/Alpha/issues/433~ Bridge
- Missing documentation https://github.com/cagov/Alpha/issues/434~ Bridge
- Product feedback List: https://github.com/cagov/Alpha/issues/559 
- Print Friendly 
- Update survey feedback form 

---------
# New User Needs

### Lifeline Services https://github.com/cagov/UX/issues/64 
- [x] Send to PUC 
- [x] Translate
- [x] Checklist for UX Design upgrade to Alpha https://github.com/cagov/UX/issues/109
- [x] Update URL to match h1 on who-can-get-a-discounted-phone-service. (Should be "check-if-you-can-get-discounted-phone-service")

### Shelter https://github.com/cagov/UX/issues/102
- [x] Carter to make changes to mimic Food bank format 
- [x] Disclaimer- to include language to contextualize where we got the data from. This is not homelessness focused. 
- [x] Add logic which appends ", CA" to a failed query and tries it again. This fixes the currently failing test for "Paradise"
- [x] Character limit on description, suggest 250 characters (so it's cleaner)
- [x] bug- when searching Butte and pressing "enter," it shows no results, You have to select the county from the drop-down. @aaronhans 
- [x] Add an explainer sentence underneath the heading "Alerts for 95818" when someone enters a zip code. "Your zip code, 95818, is in Sacramento County."
- [x] Update URL from "find-shelter" to "find-shelters-near-you"
- [x] make shelters work with query params, see if this fixes IE11

### Cal Grant
- Update alert to March 2, 2021 [Bridge]

### random
- [x] fix whatever is wrong with food banks in legacy Edge
- [x] fix sitewide blank accordion contents in IE11
- [x] take showall js out of lifeline, move to reusable location
- add CHP incidents to road closures~ Bridge
- [x] can you search in Canada and not get an error on road closures (got this report from a user) Bridge
- [x] looks like the legacy edge polyfill is being loaded unnecessarily in chrome

### Org/Contact https://github.com/cagov/UX/issues/65
- [x] Add to staging
- [x] GovOps Contact page is wrong- it now points to https://www.govops.ca.gov/contact-us-2/ and it should point to: https://www.govops.ca.gov/contact-us/

### Water (x 2) 
Main Stories: https://github.com/cagov/UX/issues/90 and https://github.com/cagov/UX/issues/89
- [x] User test
- [x] Fact check with WB ("Safe"vs removing the word in result) 
- [x] include link to quality standards 
- [x] Put Human Right to Water testing data into API https://github.com/cagov/API/issues/19
- [x] Checklist to promote to staging: https://github.com/cagov/UX/issues/88
- [x] Add new analyte effects info
- [x] Make results shareable by saving state in url
- Use better water system url source? https://www.acwa.com/about/directory/ Beta 
- [x] Fix infinity error in 91775 due to empty MCL val causing divide by 0
- [x] remove inline styles
- [x] on water: clicking button after you already did a search and got a result wrecks page
- [x] not properly screening out analytes that have returned to compliance
**From Call with WB 2/24**
- Make sure we do point to water system (US EPA)~ Beta 
- [x] Add Consumer Confidence Report
- Show Water System Consistently~ Beta  
- [x] Include timestamp "As of DATE, your water system meets/doesn't water quality standards"

### Alerts https://github.com/cagov/UX/issues/36

- [x] Description saying that alerts are done at a county level
- [x] county from zip api does not know abourt 90001

### Unemployment Insurance 
- [x] test with 1 person that has gone through this (notes)
- [x] test through user testing
- [x] Fact-check with EDD/Labor
- [x] Translate
- Minor content updates based on feedback from EDD received 3/3/2020

### Wildfire- Top 10 Prepare https://github.com/cagov/UX/issues/98
- [x] Prototype: https://cagov.github.io/UX/steps-to-prepare-for-wildfire/
- [x] Send to our wildfire contacts
- [x] Usertesting.com
- [x] Translate
- [x] Update URL to prepare-for-a-wildfire
- [x] Update homepage link title to Prepare for a wildfire

### Wildfire- Top 10 Recovery https://github.com/cagov/UX/issues/99 
- [x] Prototype https://cagov.github.io/UX/steps-to-take-after-wildfire/
- [x] Send to wildfire contacts
- [x] https://github.com/cagov/UX/issues/125
- [x] step list expansion animation sometimes breaks functionality (component updated sitewide in Alpha)
- [x] Translate
- [x] Update URL to considerations-after-a-wildfire
- Update page title to "Considerations after a wildfire"

User stories within this: 
**ID Proof** https://github.com/cagov/UX/issues/68 

~**Debris Removal** https://github.com/cagov/UX/issues/95~ 
- [x] Address within the step/consideration

**Burned Vehicle** https://github.com/cagov/UX/issues/96 
- [x] Make edits based on DMV feedback

**Comment by abquirarte** [comment]
From last week: 

- [x] Alerts prototype - Aaron
- [x] Recruit Waterboards to help us user test water again, minor content edits - Today- after Rebecca makes changes.
- [x] User test lifeline Friday 2/14/2020 at county office and Saturday at Market (with CHHS OI). Fact check with them next week after testing. 
- [x] Shelter Data scrubbing - Carter (today)
- [x] Email DMV - Rebecca to send AQ language
- [x] Add Mark and Konstantin to slack and Github- Chad
- [x] Unemployment prototype

**Comment by abquirarte** [comment]
Moving some of these bullets to the bridge issue: https://github.com/cagov/Alpha/issues/580
Closing 387. Calling this iteration "done"
