### ISSUE TITLE
Release 1 Checklist 

### ISSUE THREAD

**Issue by abquirarte** [cagov/Alpha#93]
_As a team, we need to deliver what we have, so that we can show the incremental change of our work through each iteration and get feedback from more real users so we can get better._

**Release 1 Needs**

- [x]  @ChadABratton and @carterm  walk through pipeline process now that we are on the staging environment, (who has access and high level, what to expect)
- [x] Create a Github issue for a request if there is not one there already. If they're not enough to be their own issue, document here and label the number.
- [x] Test swap
- [x] Finish baselining https://github.com/cagov/Alpha/issues/93#issuecomment-572756580 

**DOCUMENT STATUS, GITHUB ISSUE, REQUESTS**

### 1. Homepage 
**Link:** https://staging.alpha.technology.ca.gov/ 

**Github Issues:** 
- [x] #90 
- [x] #72 
- [x] #49 
- [x] #111  
- [x] # 55 in UX https://github.com/cagov/UX/issues/55

### 2. Feedback Form (@carterm) 
**Link:** https://staging.alpha.technology.ca.gov/feedback/

**Github Links**: 
- [x] #41 
- [x] #92 
- [x] #82 
- [x] #74 
- [x] Art to check for accessibility

### 3. Banner 
**Github:**
- [x] #75 
- [x] #48 

### 4. About Page 
**Link:** https://staging.alpha.technology.ca.gov/about/
- [x] Translate (Oriel) [Document](https://drive.google.com/open?id=1koCGLMttGVZe0ZssCukB9bajjXOyoaFapHyoxdQ3RU8)
- [x]  Art to check for accessibility

**Github:**
- [x] #81 

### 5. Survey (general) (@hilaryhb) -
**Link:** https://staging.alpha.technology.ca.gov/feedback/

**Github:** 
- [x] #69

### 6. Spanish Language (@orielgomez) - 
**Github:** 
- [x] https://github.com/cagov/UX/issues/55 
- [x] Survey in Spanish ->  https://github.com/cagov/UX/issues/63

### 7. News Content Type (@lukefretwell)

**Github:**
- [x] #19 
- [x] #69
- [x] migrate old content
- [x] templatize 
- [x] schedule meeting to go over new process with JP 
- [x] https://github.com/cagov/cwds/issues/19
- [x] Migrate content to News HTML (Art)
- [x] Structure and link to alpha.ca.gov/news (Art/Carter)

### 8. QA Needs for all the pages (@aaronhans )
**Github:** 

- [x] https://github.com/cagov/Alpha/issues/72#issuecomment-570320755

See comment below too! 

[Browser Testing: ](https://docs.google.com/spreadsheets/d/1jIU0bRGKC4WlODOV2Od95M5Q9Q3c6lW4Wx4lspPxVaw/edit#gid=0)
- [x] Done

### 9. Other Development Needs (@ChadABratton )

**Github:** 
- [x] https://github.com/cagov/UX/issues/54
- [x] #71
- [x] #97

### 10. Comms Needs (@jpetrucione ) 
**link** draft here: https://docs.google.com/document/d/1kcja3fqoM-bcjN1aBEJB4X3qJfkBXmR_9moIWoZLZXA/edit?ts=5e1677d6# 

- [x] Angie to review by Sunday 
- [x] Share with Art (to convert to HTML)

### 11. Minimum Wage Page 
**link** https://staging.alpha.technology.ca.gov/services/minimum-wage-in-california/

**Github:**
- [x] Accordion not working properly, please separate HTML structure from function
- [x] Novato in July 1st 2020 repeats the word "employees" (2x) @humancenteredhuman @artuoma 
- [x] #43
- [x] #19
- [x] #69
- [x] #76
- [x] https://github.com/cagov/UX/issues/55

### 12. State Holidays 
**link** https://staging.alpha.technology.ca.gov/services/state-of-california-employee-holidays/

**Github:** 
- [x] #70 
- [x] #78
- [x] https://github.com/cagov/UX/issues/55
- [x] FunctionApps https://github.com/cagov/FunctionApps/issues/6 
- [x] Oriel to confirm syntax with Aaron in ES page
- [x] Art to check for accessibility

### 13. Birth Certificate  
**link** https://staging.alpha.technology.ca.gov/services/california-birth-certificate/

**Github:** 
- [x] #53
- [x] https://github.com/cagov/UX/issues/55 
- [x] #77  
- [x] #45 

### 14. Food Banks
**link** https://staging.alpha.technology.ca.gov/services/find-food-banks-near-you/

**Github:** 
- [x] #33 
- [x] #46 
- [x] #49 
- [x] #40 
- [x] https://github.com/cagov/UX/issues/55
- [x] the 415 number still links to a call not text on food bank page
- [x] Art to check for accessibility

### 15. Licensed Contractors 
**link** https://staging.alpha.technology.ca.gov/services/hire-a-licensed-contractor/

**Github:** 
- [x] #38 
- [x] #48 
- [x] #28 
- [x] https://github.com/cagov/UX/issues/55
- [x] #27 

**Hire a licensed contractor**
@artuoma 

Possible changes based on user feedback:
- [x] Bullet points instead of lines? 
- [x] Deleting icons in steps 2 and 3?
- [x] "And" nested under step 6? (Art- I feel like we should leave it and get more feedback)

**Comment by aaronhans** [comment]
Looking forward to getting some help from the team reviewing the latest site in multiple browsers/devices

Blockers to be addressed before we can begin cross browser testing:
- [ ] create transpiled javascript bundle with polyfills for IE11
- [ ] conditionally load transpiled bundle for non ES6 browsers
- [ ] add web component polyfills for legacy edge (only load if support check fails in main bundle)

**Comment by abquirarte** [comment]
Additional tasks:

- [ ] Updating Standardize Baseline for user stories
- [ ]

**Comment by humancenteredhuman** [comment]
- [ ] Updating URL names to match h1 and delete propositions and articles:

- [ ] find-your-minimum-wage
- [ ] state-california-employee-holidays
- [ ] request-birth-certificate
- [ ] hire-licensed-contractor-home-improvements

**Comment by abquirarte** [comment]
Other items:

- [ ]  Reach out to others to verify translations (once ready @orielgomez)
- [ ]  Baseline User Stories based on the template (@jpetrucione @abquirarte @orielgomez @KimberlyglennTSM )

**Comment by abquirarte** [comment]
[Cross Browser Testing Tracking Document](https://docs.google.com/spreadsheets/d/1jIU0bRGKC4WlODOV2Od95M5Q9Q3c6lW4Wx4lspPxVaw/edit#gid=0)

**Comment by abquirarte** [comment]
> Looking forward to getting some help from the team reviewing the latest site in multiple browsers/devices
> 
> Blockers to be addressed before we can begin cross browser testing:
> 
> * [ ]  create transpiled javascript bundle with polyfills for IE11
> * [ ]  conditionally load transpiled bundle for non ES6 browsers
> * [ ]  add web component polyfills for legacy edge (only load if support check fails in main bundle)

@aaronhans - Guessing these checkmarks are done since we are testing? 

Here is the doc: https://docs.google.com/spreadsheets/d/1jIU0bRGKC4WlODOV2Od95M5Q9Q3c6lW4Wx4lspPxVaw/edit#gid=0

**Comment by abquirarte** [comment]
For documentation :) 
![image](https://user-images.githubusercontent.com/9556188/72123570-890f4d80-3316-11ea-9508-49d3b8d52521.png)

**Comment by abquirarte** [comment]
Feedback from @MikeWilkening :) 

![image](https://user-images.githubusercontent.com/9556188/72171139-2ace8300-3387-11ea-867c-2899026298a9.png)

We are a bit contradicting in the banner, (saying it's an experiment, then below showing it's "official" 

Can we make the "this is an experiment" part a bit more clear? @artuoma @lukefretwell

**Comment by humancenteredhuman** [comment]
**Alpha.CA.gov is a work in progress.** 

We welcome [your feedback](url). Thanks for helping us make government services easier to use. If you need the current site, please visit CA.gov.

**Comment by abquirarte** [comment]
Closing this! Yay team ❤️
